// Generated by gencpp from file create_msgs/DefineSong.msg
// DO NOT EDIT!


#ifndef CREATE_MSGS_MESSAGE_DEFINESONG_H
#define CREATE_MSGS_MESSAGE_DEFINESONG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace create_msgs
{
template <class ContainerAllocator>
struct DefineSong_
{
  typedef DefineSong_<ContainerAllocator> Type;

  DefineSong_()
    : song(0)
    , length(0)
    , notes()
    , durations()  {
    }
  DefineSong_(const ContainerAllocator& _alloc)
    : song(0)
    , length(0)
    , notes(_alloc)
    , durations(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _song_type;
  _song_type song;

   typedef uint8_t _length_type;
  _length_type length;

   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _notes_type;
  _notes_type notes;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _durations_type;
  _durations_type durations;





  typedef boost::shared_ptr< ::create_msgs::DefineSong_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::create_msgs::DefineSong_<ContainerAllocator> const> ConstPtr;

}; // struct DefineSong_

typedef ::create_msgs::DefineSong_<std::allocator<void> > DefineSong;

typedef boost::shared_ptr< ::create_msgs::DefineSong > DefineSongPtr;
typedef boost::shared_ptr< ::create_msgs::DefineSong const> DefineSongConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::create_msgs::DefineSong_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::create_msgs::DefineSong_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::create_msgs::DefineSong_<ContainerAllocator1> & lhs, const ::create_msgs::DefineSong_<ContainerAllocator2> & rhs)
{
  return lhs.song == rhs.song &&
    lhs.length == rhs.length &&
    lhs.notes == rhs.notes &&
    lhs.durations == rhs.durations;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::create_msgs::DefineSong_<ContainerAllocator1> & lhs, const ::create_msgs::DefineSong_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace create_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::create_msgs::DefineSong_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::create_msgs::DefineSong_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::create_msgs::DefineSong_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::create_msgs::DefineSong_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::create_msgs::DefineSong_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::create_msgs::DefineSong_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::create_msgs::DefineSong_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ae0ef1f2fad74bf546a9e5f037c27a5d";
  }

  static const char* value(const ::create_msgs::DefineSong_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xae0ef1f2fad74bf5ULL;
  static const uint64_t static_value2 = 0x46a9e5f037c27a5dULL;
};

template<class ContainerAllocator>
struct DataType< ::create_msgs::DefineSong_<ContainerAllocator> >
{
  static const char* value()
  {
    return "create_msgs/DefineSong";
  }

  static const char* value(const ::create_msgs::DefineSong_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::create_msgs::DefineSong_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 song            # song number [0-3]\n"
"uint8 length          # song length [1-16]\n"
"uint8[] notes         # notes defined by the MIDI note numbering scheme. Notes outside the range of [31-127] are rest notes.\n"
"float32[] durations   # durations in seconds. Maximum duration is 255/64.\n"
;
  }

  static const char* value(const ::create_msgs::DefineSong_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::create_msgs::DefineSong_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.song);
      stream.next(m.length);
      stream.next(m.notes);
      stream.next(m.durations);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DefineSong_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::create_msgs::DefineSong_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::create_msgs::DefineSong_<ContainerAllocator>& v)
  {
    s << indent << "song: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.song);
    s << indent << "length: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.length);
    s << indent << "notes[]" << std::endl;
    for (size_t i = 0; i < v.notes.size(); ++i)
    {
      s << indent << "  notes[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.notes[i]);
    }
    s << indent << "durations[]" << std::endl;
    for (size_t i = 0; i < v.durations.size(); ++i)
    {
      s << indent << "  durations[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.durations[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CREATE_MSGS_MESSAGE_DEFINESONG_H
