// Generated by gencpp from file create_msgs/Mode.msg
// DO NOT EDIT!


#ifndef CREATE_MSGS_MESSAGE_MODE_H
#define CREATE_MSGS_MESSAGE_MODE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace create_msgs
{
template <class ContainerAllocator>
struct Mode_
{
  typedef Mode_<ContainerAllocator> Type;

  Mode_()
    : header()
    , mode(0)  {
    }
  Mode_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , mode(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _mode_type;
  _mode_type mode;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(MODE_OFF)
  #undef MODE_OFF
#endif
#if defined(_WIN32) && defined(MODE_PASSIVE)
  #undef MODE_PASSIVE
#endif
#if defined(_WIN32) && defined(MODE_SAFE)
  #undef MODE_SAFE
#endif
#if defined(_WIN32) && defined(MODE_FULL)
  #undef MODE_FULL
#endif

  enum {
    MODE_OFF = 0u,
    MODE_PASSIVE = 1u,
    MODE_SAFE = 2u,
    MODE_FULL = 3u,
  };


  typedef boost::shared_ptr< ::create_msgs::Mode_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::create_msgs::Mode_<ContainerAllocator> const> ConstPtr;

}; // struct Mode_

typedef ::create_msgs::Mode_<std::allocator<void> > Mode;

typedef boost::shared_ptr< ::create_msgs::Mode > ModePtr;
typedef boost::shared_ptr< ::create_msgs::Mode const> ModeConstPtr;

// constants requiring out of line definition

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::create_msgs::Mode_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::create_msgs::Mode_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::create_msgs::Mode_<ContainerAllocator1> & lhs, const ::create_msgs::Mode_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.mode == rhs.mode;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::create_msgs::Mode_<ContainerAllocator1> & lhs, const ::create_msgs::Mode_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace create_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::create_msgs::Mode_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::create_msgs::Mode_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::create_msgs::Mode_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::create_msgs::Mode_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::create_msgs::Mode_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::create_msgs::Mode_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::create_msgs::Mode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b4faf4b68b6555d4656417971bee31a0";
  }

  static const char* value(const ::create_msgs::Mode_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb4faf4b68b6555d4ULL;
  static const uint64_t static_value2 = 0x656417971bee31a0ULL;
};

template<class ContainerAllocator>
struct DataType< ::create_msgs::Mode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "create_msgs/Mode";
  }

  static const char* value(const ::create_msgs::Mode_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::create_msgs::Mode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 MODE_OFF=0\n"
"uint8 MODE_PASSIVE=1\n"
"uint8 MODE_SAFE=2\n"
"uint8 MODE_FULL=3\n"
"\n"
"Header header\n"
"uint8 mode\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::create_msgs::Mode_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::create_msgs::Mode_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Mode_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::create_msgs::Mode_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::create_msgs::Mode_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CREATE_MSGS_MESSAGE_MODE_H
