// Generated by gencpp from file create_msgs/MotorSetpoint.msg
// DO NOT EDIT!


#ifndef CREATE_MSGS_MESSAGE_MOTORSETPOINT_H
#define CREATE_MSGS_MESSAGE_MOTORSETPOINT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace create_msgs
{
template <class ContainerAllocator>
struct MotorSetpoint_
{
  typedef MotorSetpoint_<ContainerAllocator> Type;

  MotorSetpoint_()
    : duty_cycle(0.0)  {
    }
  MotorSetpoint_(const ContainerAllocator& _alloc)
    : duty_cycle(0.0)  {
  (void)_alloc;
    }



   typedef float _duty_cycle_type;
  _duty_cycle_type duty_cycle;





  typedef boost::shared_ptr< ::create_msgs::MotorSetpoint_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::create_msgs::MotorSetpoint_<ContainerAllocator> const> ConstPtr;

}; // struct MotorSetpoint_

typedef ::create_msgs::MotorSetpoint_<std::allocator<void> > MotorSetpoint;

typedef boost::shared_ptr< ::create_msgs::MotorSetpoint > MotorSetpointPtr;
typedef boost::shared_ptr< ::create_msgs::MotorSetpoint const> MotorSetpointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::create_msgs::MotorSetpoint_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::create_msgs::MotorSetpoint_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::create_msgs::MotorSetpoint_<ContainerAllocator1> & lhs, const ::create_msgs::MotorSetpoint_<ContainerAllocator2> & rhs)
{
  return lhs.duty_cycle == rhs.duty_cycle;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::create_msgs::MotorSetpoint_<ContainerAllocator1> & lhs, const ::create_msgs::MotorSetpoint_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace create_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::create_msgs::MotorSetpoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::create_msgs::MotorSetpoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::create_msgs::MotorSetpoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::create_msgs::MotorSetpoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::create_msgs::MotorSetpoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::create_msgs::MotorSetpoint_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::create_msgs::MotorSetpoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6b1e8af79e9957aa39f0d7274f652afb";
  }

  static const char* value(const ::create_msgs::MotorSetpoint_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6b1e8af79e9957aaULL;
  static const uint64_t static_value2 = 0x39f0d7274f652afbULL;
};

template<class ContainerAllocator>
struct DataType< ::create_msgs::MotorSetpoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "create_msgs/MotorSetpoint";
  }

  static const char* value(const ::create_msgs::MotorSetpoint_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::create_msgs::MotorSetpoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# For the main and side brush motors, provide a duty cycle in the range [-1, 1]\n"
"# The range of acceptable values for the vacuum motor is [0, 1]\n"
"float32 duty_cycle\n"
;
  }

  static const char* value(const ::create_msgs::MotorSetpoint_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::create_msgs::MotorSetpoint_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.duty_cycle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MotorSetpoint_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::create_msgs::MotorSetpoint_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::create_msgs::MotorSetpoint_<ContainerAllocator>& v)
  {
    s << indent << "duty_cycle: ";
    Printer<float>::stream(s, indent + "  ", v.duty_cycle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CREATE_MSGS_MESSAGE_MOTORSETPOINT_H
